package com.medgo.member.domain.response;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class MaternityBenefitsResponse {
    private Integer preForBilling;
    private String noEmp;
    private String noEmpDep;
    private Boolean eligStd;
    private String principal;
    private String depSpouse;
    private String depChildren;
    private String depParents;
    private String depBrosSis;
    private String depNote;
    private Boolean mpStgItg;
    private Boolean mpExclusive;
    private String mpRmBoard;
    private Boolean mpAuto;
    private String mabFor;
    private Boolean mabIncPremium;
    private String mabOptional;
    private String mabOptPayable;
    private String mabNoMarriedFml;
    private String mabNoMarriedMl;
    private String mabNormDelivery;
    private String mabCaearean;
    private String mabAbort;
    private String mabHomeDelivery;
    private String mabAbnormal;
    private String mabOthers;
    private Boolean ecuOut;
    private Boolean ecuIncl;
    private String ecuOptional;
    private Boolean ecuIn;
    private String ecuFor;
    private String ecuAt;
    private String ecuBasis;
    private String ecuOthers;
    private Boolean posOpt;
    private Boolean posOutPatient;
    private Boolean posInPatient;
    private String posConsult;
    private String posProfFee;
    private String posLabExam;
    private String posHospBillDeduct;
    private String addAmbuPric;
    private String posHospBillCoPayment;
    private String addAmbuPer;
    private String addAmbuBen;
    private String preEmp;
    private String preEmpPrice;
    private String preEmpExpRefund;
    private String preEmpFastPer;
    private String preEmpFastPrice;
    private String agentsNotes;
    private String agentOthers;
    private String mpInCase;
    private Boolean rspClause;
    private Boolean mpMedicare;
    private String posFor;
    private String principalTo;
    private String depSpouseTo;
    private String depChildrenTo;
    private String depParentsTo;
    private String depBrosSisTo;
    private Integer depChildrenUnit;
    private Integer depChildrenToUnit;
    private Integer depBrosSisUnit;
    private Integer depBrosSisToUnit;
    private String addRates;
    private Boolean mpPhil;
    private Boolean rspNoNew;
    private String preEmpExpPercent;
    private String opcsPrepostNatalPrn;
    private String opcsPrepostNatalDep;
    private String opcsPrepostNatalExt;
    private String mpOthers;
    private Integer vatExempt;
    private Integer zeroRated;
    private Integer preCashBasis;
}