
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shared-reimbursement-chart.name" . }}-creds
  labels:
    app: {{ include "shared-reimbursement-chart.name" . }}
type: Opaque
data:
  application.properties: |
{{ .Values.appProperties | b64enc | indent 4 }}

