
trigger: none
pr: none

variables:
  servicePath: 'services/shared-utilization-service'
  chartPath: 'services/shared-utilization-service/shared-utilization-chart'
  dockerRegistry: 'Medgo2.0ACR_SVC_Connection-12-01-26'
  imageName: 'shared-utilization-service-stg'
  #dockerRegistryEndpoint: 'acrmpiseaashared01'
  imagePullSecrets: 'medgopullsecret'
  aksCluster: 'aks-mpi-sea-a-shared01'
  aksResourceGroup: 'rg-mpi-sea-d-shared-aks01'
  azureSubscription: 'medgo2_sharedaks_svc_connection'
  acrName: 'acrmpiseaashared01.azurecr.io'
  propsfile: 'shared-utilization'

stages:
# ------------------------------
#  Build / Scan Stage
# ------------------------------
- stage: Build
  displayName: "Image - Build, Scan and Push"
  jobs:
  - template: templates/build.yaml
    parameters:
      servicePath: $(servicePath)
      dockerRegistry: $(dockerRegistry)
      imageName: $(imageName)
      acrName: $(acrName)

# ------------------------------
#  Deploy Stage
# ------------------------------
- stage: Deploy
  displayName: "Deploy to AKS"
  dependsOn: Build
  variables:
    # Option to override the default AKS for testing/new environment
    # Change this value to 'new' to deploy to alternate RG + AKS
    targetEnvironment: 'shared'   # valid values: 'prod', 'external', or 'shared'
  jobs:
  - template: templates/deploy.yaml
    parameters:
      dockerRegistryEndpoint: $(dockerRegistry)
      imagePullSecrets: $(imagePullSecrets)
      imageName: $(imageName)
      azureSubscription: $(azureSubscription)
      serviceName: $(propsfile)
      chartPath: $(chartPath)
      propsfile: $(propsfile)
      targetEnvironment: $(targetEnvironment)
