version: '3.8'
networks:
  com.medgo.membernwk:
    name: app
    driver: bridge
volumes:
  postgres_data:
    driver: local
services:
  member-service:
    image: com.medgo/member-service:0.1.0
    container_name: member-service
    ports:
      - "11255:11255"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/memberservicedb
      SPRING_DATASOURCE_PASSWORD: swCLgMNkOZHr
    networks:
      - com.medgo.membernwk
    depends_on:
      - db
    
  db:
    image: postgres:12.6
    container_name: com.medgo.memberdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - com.medgo.membernwk
    ports:
      - "17788:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: swCLgMNkOZHr
      POSTGRES_DB: memberservicedb
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2
  