
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "provider-chart.name" . }}-deploy
  labels:
    app: {{ include "provider-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "provider-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "provider-chart.name" . }}
    spec:
      containers:
      - name: provider-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/app/
        - name: app-config
          mountPath: /application/BOOT-INF/classes/{{ .Values.env.name }}
          subPath: application.properties
          readOnly: true
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
      - name: app-config
        secret:
          secretName: {{ include "provider-chart.name" . }}-creds
          items:
            - key: application.properties
              path: application.properties
