version: '3.8'
networks:
  com.medgo.communicationnwk:
    name: app
    driver: bridge
volumes:
  postgres_data:
    driver: local
services:
  communication-service:
    image: com.medgo/communication-service:0.1.0
    container_name: communication-service
    ports:
      - "11151:11151"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/communicationservicedb
      SPRING_DATASOURCE_PASSWORD: hGsqLhRODpoB
    networks:
      - com.medgo.communicationnwk
    depends_on:
      - db
    
  db:
    image: postgres:12.6
    container_name: com.medgo.communicationdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - com.medgo.communicationnwk
    ports:
      - "19831:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hGsqLhRODpoB
      POSTGRES_DB: communicationservicedb
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2
  